# Generated by Django 2.2.3 on 2019-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny_path', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
