# Generated by Django 2.2.3 on 2019-07-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny_path', '0003_auto_20190703_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='trail',
            name='amenities',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='difficulty',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='park_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
