# Generated by Django 2.2.3 on 2019-07-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiny_path', '0010_auto_20190710_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Googlemap',
        ),
    ]
