# Generated by Django 2.2.3 on 2019-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny_path', '0011_auto_20190711_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='cover',
        ),
        migrations.AddField(
            model_name='trail',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='reference_id',
            field=models.IntegerField(null=True),
        ),
    ]
